import type { Chore } from '@customTypes/SharedTypes';

// Sample data, TODO: pull from Express
export const database: Chore[] = [
    {
        id: 1,
        name: 'Vacuum Bedroom Floor',
        room: 'Bedroom',
        dateLastCompleted: new Date("2025-06-12"),
        duration: 20,
        frequency: 7,
    },
    {
        id: 2,
        name: 'Vacuum Living Room Floor',
        room: 'Living Room',
        dateLastCompleted: new Date("2025-06-12"),
        duration: 20,
        frequency: 7,
    },
    {
        id: 3,
        name: 'Vacuum Kitchen Floor',
        room: 'Kitchen',
        dateLastCompleted: new Date("2025-06-12"),
        duration: 20,
        frequency: 7,
    },
    {
        id: 4,
        name: 'Change Bedsheets',
        room: 'Bedroom',
        dateLastCompleted: new Date("2025-06-09"),
        duration: 10,
        frequency: 7,
    },
    {
        id: 5,
        name: 'Change Towels',
        room: 'Bathroom',
        dateLastCompleted: new Date("2025-06-13"),
        duration: 2,
        frequency: 3,
    },
    {
        id: 6,
        name: 'Sweep Kitchen Floor',
        room: 'Kitchen',
        dateLastCompleted: new Date("2025-06-14"),
        duration: 3,
        frequency: 2,
    },
    {
        id: 7,
        name: 'Sweep Sunroom Floor',
        room: 'Sunroom',
        dateLastCompleted: new Date("2025-05-31"),
        duration: 7,
        frequency: 30,
    },
    {
        id: 8,
        name: 'Mop Kitchen Floor',
        room: 'Kitchen',
        dateLastCompleted: new Date("2025-06-09"),
        duration: 45,
        frequency: 7,
    },
    {
        id: 9,
        name: 'Clean Bathroom',
        room: 'Bathroom',
        dateLastCompleted: new Date("2025-06-10"),
        duration: 60,
        frequency: 7,
    },
    {
        id: 10,
        name: 'HVAC Air Filter Replacement',
        details: 'Replace the air filter in the HVAC system to ensure proper airflow and air quality.',
        room: 'Basement',
        dateLastCompleted: new Date("2025-03-31"),
        duration: 10,
        frequency: 90,
        urgency: 'low',
        longTermTask: true,
    },
];
