import type { Chore } from '@customTypes/SharedTypes';

// Sample data, TODO: pull from Express
export const choreData: Chore[] = [
    {
        id: 1,
        name: 'Vacuum Floors',
        category: ['Bedroom', 'Living Room', 'Kitchen'],
        dateLastCompleted: new Date("2025-06-12"),
        duration: 20,
        frequency: 7,
        hidden: false,
    },
    {
        id: 2,
        name: 'Change Bedsheets',
        category: ['Bedroom'],
        dateLastCompleted: new Date("2025-06-09"),
        duration: 10,
        frequency: 7,
        hidden: false,
    },
    {
        id: 3,
        name: 'Change Towels',
        category: ['Bathroom'],
        dateLastCompleted: new Date("2025-06-13"),
        duration: 2,
        frequency: 3,
        hidden: false,
    },
    {
        id: 4,
        name: 'Sweep Kitchen Floor',
        category: ['Kitchen'],
        dateLastCompleted: new Date("2025-06-14"),
        duration: 3,
        frequency: 2,
        hidden: false,
    },
    {
        id: 5,
        name: 'Sweep Sunroom Floor',
        category: ['Sunroom'],
        dateLastCompleted: new Date("2025-05-31"),
        duration: 7,
        frequency: 30,
        hidden: false,
    },
    {
        id: 6,
        name: 'Mop Floors',
        category: ['Kitchen'],
        dateLastCompleted: new Date("2025-06-09"),
        duration: 45,
        frequency: 7,
        hidden: false,
    },
    {
        id: 7,
        name: 'Clean Bathroom',
        category: ['Bathroom'],
        dateLastCompleted: new Date("2025-06-10"),
        duration: 60,
        frequency: 7,
        hidden: false,
    },
    {
        id: 8,
        name: 'HVAC Air Filter Replacement',
        details: 'Replace the air filter in the HVAC system to ensure proper airflow and air quality.',
        category: ['Basement'],
        dateLastCompleted: new Date("2025-03-31"),
        duration: 10,
        frequency: 90, // every 3 months
        hidden: false,
    },
];